// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKQwXQbgU5JlbGb0_nwyUPJNOQlgGM_Y',
    appId: '1:450382378984:android:8a5c73f410e3cedb4a165d',
    messagingSenderId: '450382378984',
    projectId: 'fresh-cart-69ec4',
    storageBucket: 'fresh-cart-69ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPBlg28xqkbE28vjV9k70GCs4XAsRZJU',
    appId: '1:450382378984:ios:e02c399158b59a384a165d',
    messagingSenderId: '450382378984',
    projectId: 'fresh-cart-69ec4',
    storageBucket: 'fresh-cart-69ec4.firebasestorage.app',
    iosBundleId: 'com.example.freshcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPBlg28xqkbE28vjV9k70GCs4XAsRZJU',
    appId: '1:450382378984:ios:e02c399158b59a384a165d',
    messagingSenderId: '450382378984',
    projectId: 'fresh-cart-69ec4',
    storageBucket: 'fresh-cart-69ec4.firebasestorage.app',
    iosBundleId: 'com.example.freshcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmytY292R_U9YAtKbXr6fuvD8EtDhztrM',
    appId: '1:450382378984:web:6362bae46c67d2ee4a165d',
    messagingSenderId: '450382378984',
    projectId: 'fresh-cart-69ec4',
    authDomain: 'fresh-cart-69ec4.firebaseapp.com',
    storageBucket: 'fresh-cart-69ec4.firebasestorage.app',
    measurementId: 'G-7HC1MR2P2B',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmytY292R_U9YAtKbXr6fuvD8EtDhztrM',
    appId: '1:450382378984:web:6362bae46c67d2ee4a165d',
    messagingSenderId: '450382378984',
    projectId: 'fresh-cart-69ec4',
    authDomain: 'fresh-cart-69ec4.firebaseapp.com',
    storageBucket: 'fresh-cart-69ec4.firebasestorage.app',
    measurementId: 'G-7HC1MR2P2B',
  );
}
